services:
  django:
    image: ${DOCKER_USER}/${DOCKER_IMG1}:${TAG1}
    restart: unless-stopped
    platform: linux/amd64
    container_name: django_app
    command: /start.sh
    ports:
      - "127.0.0.1:8000:8000" 
    env_file:
      - .env.main
    environment:
      - TIKA_CLIENT_ONLY=True
      - TIKA_SERVER_ENDPOINT=http://tika:9998
    depends_on:
      - tika  
    
  tika:
    image: apache/tika
    restart: unless-stopped
    platform: linux/amd64
    container_name: tika_server
    ports:
      - "9998:9998"

  rasa:
    image: ${DOCKER_USER}/${DOCKER_IMG2}:${TAG2} 
    container_name: rasa_server
    ports:
      - "5005:5005"
    depends_on:
      - actions
    
  actions:
    image: ${DOCKER_USER}/${DOCKER_IMG3}:${TAG3}
    container_name: rasa_actions
    ports:
      - "5055:5055"
    env_file:
      - .env.main

