# Generated by Django 5.1.1 on 2026-09-01 02:38

import mysite.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_name', models.CharField(blank=True, default='', max_length=100)),
                ('certification_icon', models.FileField(default='', storage=mysite.models.OverwriteStorage(), upload_to='certifications')),
                ('verification_url', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('message', models.TextField(blank=True, max_length=2500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience_rank', models.IntegerField(blank=True, default=99)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=20)),
                ('role', models.CharField(default='', max_length=50)),
                ('timeline', models.CharField(blank=True, default='', max_length=20)),
                ('project_title', models.CharField(blank=True, default='', max_length=200)),
                ('company_experience', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file_name', models.CharField(blank=True, default='resume', max_length=20)),
                ('resume_file', models.FileField(blank=True, default='', storage=mysite.models.OverwriteStorage(), upload_to='cv')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.IntegerField(blank=True, default=99)),
                ('project_category', models.CharField(blank=True, default='', max_length=50)),
                ('project_name', models.CharField(default='', max_length=200)),
                ('timeline', models.CharField(blank=True, default='', max_length=20)),
                ('project_description', models.TextField(blank=True, default='')),
                ('project_image', models.ImageField(blank=True, null=True, storage=mysite.models.OverwriteStorage(), upload_to='project_images')),
                ('project_doc', models.FileField(blank=True, default='', storage=mysite.models.OverwriteStorage(), upload_to='projects')),
                ('tools', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('column_number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('skill_icon', models.FileField(default='', upload_to='skills')),
                ('description', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(blank=True, default='', max_length=100)),
                ('tool_category', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tool_icon', models.FileField(default='', storage=mysite.models.OverwriteStorage(), upload_to='tools')),
            ],
        ),
    ]
