# Generated by Django 4.1 on 2024-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_certification_certification_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_logo',
            field=models.FileField(default='', upload_to='media/certifications'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_logo',
            field=models.FileField(default='', upload_to='media/tools'),
        ),
    ]
