# Generated by Django 4.1 on 2024-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_certification_certification_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='verification_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification_logo',
            field=models.FileField(default='', upload_to='certifications'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_logo',
            field=models.FileField(default='', upload_to='tools'),
        ),
    ]
