# Generated by Django 4.1 on 2024-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
