# Generated by Django 4.1 on 2024-08-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_contactform_name_contactform_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='id',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
