# Generated by Django 4.1 on 2024-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_experience',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
