# Generated by Django 4.1 on 2024-09-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_experience_company_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_experience',
            field=models.CharField(blank=True, default='', max_length=2500),
        ),
    ]
