# Generated by Django 4.1 on 2024-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_experience_company_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
