# Generated by Django 4.1 on 2024-09-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='timeline',
            field=models.CharField(default='', max_length=20),
        ),
    ]
