# Generated by Django 4.1 on 2024-09-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_experience_role_experience_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='timeline',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
