name: Deploy Django Application
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image 
        run: ./automation/docker-build.sh "${{ vars.DOCKER_USER }}" "${{ vars.IMG_TAG }}"
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - name: Print 
        run: echo "Docker image built successfully."
  
  sync-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ vars.EC2_HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.EC2_KEY }}" > /tmp/portfolio-ec2.pem
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod 600 .env
          chmod 600 /tmp/portfolio-ec2.pem
          echo "SSH and environment configuration completed successfully."
      - name: Sync assets to EC2
        run: ./automation/sync-assets.sh
        env:
          KEY: /tmp/portfolio-ec2.pem
      - name: Confirm asset sync
        run: echo "Static files, media, environment, and deployment configuration successfully synced to EC2."
      
  ec2-cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login into EC2
        uses: appleboy/ssh-action@v1.2.2
        with: 
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Logged into EC2 successfully"
            docker ps -a
            ./docker-clean.sh

  deploy:
    runs-on: ubuntu-latest
    needs: ec2-cleanup
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}    
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deploying to EC2..."
            docker compose --env-file .env up -d
